# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: Default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- powershell: 'labview-cli --lv-ver 2014 "C:\CLIDemo2.vi"'
- script: 
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
